theme: jekyll-theme-minimal
title: Dr Kirsty McGhee
description: Technical and scientific writer specialising in software for quantum computing research, with a PhD in materials science and photonics.

github:
  is_project_page: false

show_github: false

navigation:
  - title: Home
    url: /
  - title: Technical documentation
    url: /technical-documentation/
  - title: Scientific writing
    url: /scientific-writing/
  - title: Marketing & communications
    url: /marketing/
  - title: Research publications
    url: /research-publications/
  - title: Podcast interviews
    url: /podcast-interviews/
